
apiVersion: v1
kind: Service

metadata:
    name: {{.Values.serviceName}}
    labels:
        run: {{.Values.serviceName}}
    namespace: {{.Values.namespace}}

spec:
    {{- $serviceMap := index .Values.services .Values.serviceName}}
    {{- $serviceType := index $serviceMap "type"}}
    type: {{$serviceType}}
    selector:
        run: {{.Values.serviceName}}
    ports:
    - port: {{index $serviceMap "externalPort"}}
      protocol: TCP
      targetPort: {{.Values.containerPort}}
    {{- if eq $serviceType "LoadBalancer"}}
    loadBalancerIP: {{index $serviceMap "host"}}
    {{- end}}

